# apiVersion: skaffold/v4beta1
# kind: Config
# build:
#   googleCloudBuild:
#     projectId: ticketing-dev-385109
#   artifacts:
#     - image: us.gcr.io/ticketing-dev-385109/auth
#       context: auth
#       sync:
#         manual:
#           - src: src/**/*.ts
#             dest: .
#       docker:
#         dockerfile: Dockerfile
#   local:
#     push: false
# manifests:
#   rawYaml:
#     - ./infra/k8s/*

apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-385109
  artifacts:
    - image: us.gcr.io/ticketing-dev-385109/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
